server:
  port: 9001


spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: oracle.jdbc.driver.OracleDriver              # mysql驱动包
    url: jdbc:oracle:thin:@136.5.178.78:8443:orcl
    username: zabbix
    password: Ustc9.V2019#LpswJt

eureka:
  client:
    #表示是否将自己注册进Eurekaserver默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: utils9001
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml

outfile:
  path: F:/项目资料/电信号码平台/月报/7月份