server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: cloud-payment-service
          uri:  lb://cloud-payment-service
          predicates:
            - Path=/payment/**

eureka:
  instance:
    instance-id: gateway9527
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/
